### ISSUE TITLE
Create Contributor-Form and its functionality. 

### ISSUE THREAD

**Issue by Ayush8923** [theSolution2y/thesolution2y#54]
**Is your feature request related to a problem? Please describe.**
We need to store the contributor-users. For this we will be needing a table to store the contributor details  and form submission functionality.

**Describe the solution you'd like**
- [x] Create a table `Contributor-form` .
- [x] Contributor-form submission functionality.

**Describe alternatives you've considered**
NA

**Additional context**
- https://laravel.com/docs/8.x/migrations

**Comment by balendurawat** [comment]
the functionality is not working

**Comment by balendurawat** [comment]
do it again
